server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://uuxeulvbnskoyr:16e89bd3097a99c15179d6d96b18395c7976bc93c670a613c42aad49dc0bb528@ec2-34-233-114-40.compute-1.amazonaws.com:5432/d43ghrmo87prfq
    username: uuxeulvbnskoyr
    password: 16e89bd3097a99c15179d6d96b18395c7976bc93c670a613c42aad49dc0bb528
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o bootcamp DIO - Santander / Backend